name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  cloud_firestore: ^4.15.6
  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # Ensure the indentation is correct here

