// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzoKWANf1Kno9LnrnS90F2Hw5wfFl1I4',
    appId: '1:854540743036:web:a290741ad454c9bf5cb4f9',
    messagingSenderId: '854540743036',
    projectId: 'zakat-4ab66',
    authDomain: 'zakat-4ab66.firebaseapp.com',
    storageBucket: 'zakat-4ab66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhu6K_mXNFFMEB1Qgoze5FDP_DR90ifOc',
    appId: '1:854540743036:android:d17e28e8e917c2585cb4f9',
    messagingSenderId: '854540743036',
    projectId: 'zakat-4ab66',
    storageBucket: 'zakat-4ab66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwpmOtKzAfe2nTv0PT2qYTagYNxyr8g4',
    appId: '1:854540743036:ios:582fcd451d78311a5cb4f9',
    messagingSenderId: '854540743036',
    projectId: 'zakat-4ab66',
    storageBucket: 'zakat-4ab66.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpwpmOtKzAfe2nTv0PT2qYTagYNxyr8g4',
    appId: '1:854540743036:ios:e5425815c716f9c15cb4f9',
    messagingSenderId: '854540743036',
    projectId: 'zakat-4ab66',
    storageBucket: 'zakat-4ab66.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
